-- Flyway migration V1
-- Users + follows/blocks + refresh tokens (auth)

CREATE TABLE IF NOT EXISTS users (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH TEXT NOT NULL,
    AVATAR_URL TEXT,
    BIO TEXT,
    ROLE VARCHAR(20) NOT NULL DEFAULT 'USER',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    FCM_TOKEN TEXT,
    EMBEDDING JSON,
    LAST_ACTIVE_AT DATETIME,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_follows (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FOLLOWER_ID BIGINT UNSIGNED NOT NULL,
    FOLLOWING_ID BIGINT UNSIGNED NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_follow (FOLLOWER_ID, FOLLOWING_ID),
    CONSTRAINT fk_user_follows_follower FOREIGN KEY (FOLLOWER_ID) REFERENCES users(ID) ON DELETE CASCADE,
    CONSTRAINT fk_user_follows_following FOREIGN KEY (FOLLOWING_ID) REFERENCES users(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_blocks (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    BLOCKER_ID BIGINT UNSIGNED NOT NULL,
    BLOCKED_ID BIGINT UNSIGNED NOT NULL,
    UNIQUE KEY uq_block (BLOCKER_ID, BLOCKED_ID),
    CONSTRAINT fk_user_blocks_blocker FOREIGN KEY (BLOCKER_ID) REFERENCES users(ID) ON DELETE CASCADE,
    CONSTRAINT fk_user_blocks_blocked FOREIGN KEY (BLOCKED_ID) REFERENCES users(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS refresh_tokens (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT UNSIGNED NOT NULL,
    TOKEN VARCHAR(255) NOT NULL UNIQUE,
    USER_AGENT_HASH VARCHAR(64),
    EXPIRES_AT DATETIME NOT NULL,
    REVOKED_AT DATETIME,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (USER_ID) REFERENCES users(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

